name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache node modules
      uses: actions/cache@v3
      post-if: always()
      with:
        path: |
          ~/.cargo
          ./target/
          ./Cargo.lock
        key: ${{ runner.os }}-build-cache-wasm

    - name: Install wasmpack
      run: cargo install wasm-pack

    - name: Ls
      run: ls
    #- name: Build
    #  run: cargo build --verbose
    #- name: Run tests
    #  run: cargo test --verbose
    - name: Build
      run: wasm-pack build --release --target web
    - name: Ls
      run: ls
    - name: Ls
      run: ls *
    - name: Ls
      run: ls */*
